### ISSUE TITLE
Main file error

### ISSUE THREAD

**Issue by vp8181** [luni64/TeensyStep4#5]
@KrisKasprzak @CloudHead84 @luni64 downloaded the main file but arduino ide gives error of -
(Specified folder/zip file does not contain a valid library)
Later when i manually placed that file in my libraries folder the ide gave error-
(Invalid library found in C:\Users\Vaibhav Pandey\OneDrive\Documents\Arduino\libraries\TeensyStep4: no headers files (.h) found in C:\Users\Vaibhav Pandey\OneDrive\Documents\Arduino\libraries\TeensyStep4)

**Comment by luni64** [comment]
What Version of the IDE are you using?

**Comment by vp8181** [comment]
@luni64 
Arduino IDE - 1.8.19
Teensyduino - 1.56
Windows 10

**Comment by luni64** [comment]
I added the required manifests to make the Arduino IDE happy and fixed some other issues. Downloading the zip file and adding it with the IDE should work now. I tested building the examples with the Arduino IDE, both compile and work as expected
Hope that helps

**Comment by vp8181** [comment]
@luni64
Much appreciated. It works now just need to see to if the stepper works accordingly. 
Thanks.
